import { useEffect, useMemo, useState } from 'react';
import type { Device, MonitoringRecord } from '../lib/api';
import { fetchDeviceHistory, fetchDevices, fetchMonitoring } from '../lib/api';
import type { MonitorResult } from '../types';
import { PageHeader } from '../components/PageHeader';
import { StatusIndicator } from '../components/StatusIndicator';

export function MonitoringPage({ monitorResults, onViewAlerts, reconnectKey }: { monitorResults: Map<number, MonitorResult>; onViewAlerts: () => void; reconnectKey: number }) {
  const [devices, setDevices] = useState<Device[]>([]); const [records, setRecords] = useState<MonitoringRecord[]>([]); const [selected, setSelected] = useState<MonitoringRecord | null>(null); const [history, setHistory] = useState<string>(''); const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState<'all' | MonitoringRecord['status']>('all'); const [typeFilter, setTypeFilter] = useState<'all' | Device['type']>('all'); const [error, setError] = useState('');
  useEffect(() => { void Promise.all([fetchDevices(), fetchMonitoring()]).then(([nextDevices, nextRecords]) => { setDevices(nextDevices); setRecords(nextRecords); }).catch((err: unknown) => setError(err instanceof Error ? err.message : 'Gagal memuat monitoring.')); }, [reconnectKey]);
  const live = useMemo(() => records.map((record) => { const result = monitorResults.get(record.device_id); return result ? { ...record, status: result.status, latency_ms: result.latency_ms, last_check: result.timestamp } : record; }), [records, monitorResults]);
  const filtered = live.filter((record) => (statusFilter === 'all' || record.status === statusFilter) && (typeFilter === 'all' || record.device_type === typeFilter) && (!search || `${record.device_name} ${record.ip}`.toLowerCase().includes(search.toLowerCase())));
  const choose = async (record: MonitoringRecord) => { setSelected(record); try { const records = await fetchDeviceHistory(record.device_id); setHistory(records.slice(0, 5).map((item) => `${item.status} · ${item.latency_ms} ms · ${item.timestamp}`).join('\n') || 'Belum ada riwayat.'); } catch { setHistory('Gagal memuat riwayat.'); } };
  const counts = { total: live.length, online: live.filter((item) => item.status === 'online').length, offline: live.filter((item) => item.status === 'offline').length, warning: live.filter((item) => item.status === 'warning').length };
  const detail = selected && devices.find((device) => device.id === selected.device_id);
  return <div className="max-w-[1200px] mx-auto px-4 lg:px-8 py-6 lg:py-8 space-y-5"><PageHeader title="Monitoring" subtitle={`${counts.total} devices · ${counts.online} online · ${counts.offline} offline · ${counts.warning} warning`} />{error && <p className="rounded bg-danger-muted p-3 text-sm text-danger">{error}</p>}<div className="flex flex-wrap gap-3"><input className="min-w-56 flex-1 rounded-lg border border-border bg-surface p-3 text-sm" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search device or IP..." /><select className="rounded-lg border border-border bg-surface px-3 text-sm" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as typeof statusFilter)}><option value="all">All status</option><option value="online">Online</option><option value="offline">Offline</option><option value="warning">Warning</option><option value="unknown">Unknown</option></select><select className="rounded-lg border border-border bg-surface px-3 text-sm" value={typeFilter} onChange={(event) => setTypeFilter(event.target.value as typeof typeFilter)}><option value="all">All device types</option>{['Server', 'Router', 'Switch', 'Access Point', 'Website'].map((type) => <option key={type}>{type}</option>)}</select></div><div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 rounded-xl border border-border bg-surface overflow-hidden"><table className="w-full text-sm"><thead><tr className="text-left text-text-muted"><th className="p-4">Device</th><th>Status</th><th>Latency</th><th>Last Check</th></tr></thead><tbody>{filtered.map((record) => <tr key={record.device_id} onClick={() => void choose(record)} className="cursor-pointer border-t border-border/50 hover:bg-surface-elevated"><td className="p-4"><p className="font-medium">{record.device_name}</p><p className="font-mono text-xs text-text-muted">{record.ip} · {record.device_type}</p></td><td><span className="inline-flex items-center gap-2"><StatusIndicator status={record.status === 'unknown' ? 'warning' : record.status} size="sm" />{record.status}</span></td><td className="font-mono">{record.latency_ms} ms</td><td className="text-xs text-text-muted">{record.last_check ?? '—'}</td></tr>)}</tbody></table></div><aside className="rounded-xl border border-border bg-surface p-5">{selected && detail ? <div className="space-y-3 text-sm"><h2 className="font-semibold">{detail.name}</h2><p>{detail.type} · {detail.ip}</p><p>Status: <b>{selected.status}</b></p><p>Method: {detail.method}</p><p>Interval: {detail.check_interval} seconds</p><p>{detail.description || 'No description.'}</p><pre className="whitespace-pre-wrap rounded bg-bg p-3 text-xs text-text-muted">{history}</pre>{selected.status !== 'online' && <button onClick={onViewAlerts} className="text-accent">View alerts →</button>}</div> : <p className="text-sm text-text-muted">Pilih device untuk melihat detail dan riwayat.</p>}</aside></div></div>;
}
